spring:
  datasource:
#    오라클
#    url: jdbc:oracle:thin:@localhost:1521:XE
#    username: PF
#    password: 1234
#    driver-class-name: oracle.jdbc.OracleDriver

#   Mysql
    url: jdbc:mysql://localhost:3306/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
  redis:
    host: localhost
    port: 6379

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${CLIENT_ID_KAKAO}
            client-secret: ${CLIENT_SECRET_KAKAO}
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-name: Kakao
            client-authentication-method: client_secret_post

          naver:
            client-id: ${CLIENT_ID_NAVER}
            client-secret: ${CLIENT_SECRET_NAVER}
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
            client-name: Naver
            authorization-grant-type: authorization_code
            scope: name, email

          google:
            client-id: ${CLIENT_ID_GOOGLE}
            client-secret: ${CLIENT_SECRET_GOOGLE}
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            scope: profile, email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response


logging.level:
  org.hibernate.SQL: debug
  # org.hibernate.type: trace #스프링 부트 2.x, hibernate5
  org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6

server:
  port: 8090

file:
  add: ${PATH_IMAGEADD}

admin:
  password: ${PASSWORD_ADMIN}

user:
  random:
    password: ${PASSWORD_RANDOM_USER}

